name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm lint

  build:
    runs-on: self-hosted
    needs: lint

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: $IMAGE_NAME/clockbox:latest