name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm lint

  build:
    runs-on: self-hosted
    needs: lint

    steps:
      - uses: 'docker'
      - run: docker build . -t ${{ github.event.repository.name }}